name: pr-test

on:
  pull_request:
    branches: ["*"]

jobs:
  bass:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: {submodules: true}
    - uses: actions/setup-go@v2
      with: {go-version: 1.18}
    - run: ./hack/actions-test
